# Generated by Django 4.0.4 on 2022-05-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_related_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
