# Generated by Django 4.0.4 on 2022-06-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_renewal_amount_subscription_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(db_column='subscription_name', max_length=150, unique=True),
        ),
    ]
