# Generated by Django 4.0.4 on 2022-06-06 02:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscription_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
